# 00 — Check StatsBomb Data Availability

Run this first to see exactly which competitions and seasons are available.
Note down the `competition_id` and `season_id` you want to use.

In [1]:
from statsbombpy import sb
import pandas as pd
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 20)

In [2]:
# Load all available competitions
competitions = sb.competitions()
print(f'Total competitions available: {len(competitions)}')
competitions[['competition_name', 'season_name', 'competition_id', 'season_id', 'competition_gender']].sort_values(['competition_name', 'season_name'])

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Total competitions available: 75

,competition_name,season_name,competition_id,season_id,competition_gender
1,1. Bundesliga,2015/2016,9,27,male
0,1. Bundesliga,2023/2024,9,281,male
2,African Cup of Nations,2023,1267,107,male
20,Champions League,1970/1971,16,276,male
19,Champions League,1971/1972,16,71,male
18,Champions League,1972/1973,16,277,male
17,Champions League,1999/2000,16,76,male
16,Champions League,2003/2004,16,44,male
15,Champions League,2004/2005,16,37,male
14,Champions League,2006/2007,16,39,male
13,Champions League,2008/2009,16,41,male
12,Champions League,2009/2010,16,21,male
11,Champions League,2010/2011,16,22,male
10,Champions League,2011/2012,16,23,male
9,Champions League,2012/2013,16,24,male
8,Champions League,2013/2014,16,25,male
7,Champions League,2014/2015,16,26,male
6,Champions League,2015/2016,16,27,male
5,Champions League,2016/2017,16,2,male
4,Champions League,2017/2018,16,1,male
3,Champions League,2018/2019,16,4,male
21,Copa America,2024,223,282,male
24,Copa del Rey,1977/1978,87,279,male
23,Copa del Rey,1982/1983,87,268,male
22,Copa del Rey,1983/1984,87,84,male
27,FA Women's Super League,2018/2019,37,4,female
26,FA Women's Super League,2019/2020,37,42,female
25,FA Women's Super League,2020/2021,37,90,female
28,FIFA U20 World Cup,1979,1470,274,male
36,FIFA World Cup,1958,43,269,male
35,FIFA World Cup,1962,43,270,male
34,FIFA World Cup,1970,43,272,male
33,FIFA World Cup,1974,43,51,male
32,FIFA World Cup,1986,43,54,male
31,FIFA World Cup,1990,43,55,male
30,FIFA World Cup,2018,43,3,male
29,FIFA World Cup,2022,43,106,male
37,Indian Super league,2021/2022,1238,108,male
55,La Liga,1973/1974,11,278,male
54,La Liga,2004/2005,11,37,male
53,La Liga,2005/2006,11,38,male
52,La Liga,2006/2007,11,39,male
51,La Liga,2007/2008,11,40,male
50,La Liga,2008/2009,11,41,male
49,La Liga,2009/2010,11,21,male
48,La Liga,2010/2011,11,22,male
47,La Liga,2011/2012,11,23,male
46,La Liga,2012/2013,11,24,male
45,La Liga,2013/2014,11,25,male
44,La Liga,2014/2015,11,26,male
43,La Liga,2015/2016,11,27,male
42,La Liga,2016/2017,11,2,male
41,La Liga,2017/2018,11,1,male
40,La Liga,2018/2019,11,4,male
39,La Liga,2019/2020,11,42,male
38,La Liga,2020/2021,11,90,male
57,Liga Profesional,1981,81,275,male
56,Liga Profesional,1997/1998,81,48,male
60,Ligue 1,2015/2016,7,27,male
59,Ligue 1,2021/2022,7,108,male
58,Ligue 1,2022/2023,7,235,male
61,Major League Soccer,2023,44,107,male
63,NWSL,2018,49,3,female
62,North American League,1977,116,68,male
65,Premier League,2003/2004,2,44,male
64,Premier League,2015/2016,2,27,male
67,Serie A,1986/1987,12,86,male
66,Serie A,2015/2016,12,27,male
69,UEFA Euro,2020,55,43,male
68,UEFA Euro,2024,55,282,male
70,UEFA Europa League,1988/1989,35,75,male
72,UEFA Women's Euro,2022,53,106,female
71,UEFA Women's Euro,2025,53,315,female
74,Women's World Cup,2019,72,30,female
73,Women's World Cup,2023,72,107,female

In [3]:
# Filter to men's competitions only
mens = competitions[competitions['competition_gender'] == 'male']
print(f'Men competitions: {len(mens)}')
mens[['competition_name', 'season_name', 'competition_id', 'season_id']]

Men competitions: 67

          competition_name season_name  competition_id  season_id
0            1. Bundesliga   2023/2024               9        281
1            1. Bundesliga   2015/2016               9         27
2   African Cup of Nations        2023            1267        107
3         Champions League   2018/2019              16          4
4         Champions League   2017/2018              16          1
5         Champions League   2016/2017              16          2
6         Champions League   2015/2016              16         27
7         Champions League   2014/2015              16         26
8         Champions League   2013/2014              16         25
9         Champions League   2012/2013              16         24
10        Champions League   2011/2012              16         23
11        Champions League   2010/2011              16         22
12        Champions League   2009/2010              16         21
13        Champions League   2008/2009              16         41
14        Champions League   2006/2007              16         39
15        Champions League   2004/2005              16         37
16        Champions League   2003/2004              16         44
17        Champions League   1999/2000              16         76
18        Champions League   1972/1973              16        277
19        Champions League   1971/1972              16         71
20        Champions League   1970/1971              16        276
21            Copa America        2024             223        282
22            Copa del Rey   1983/1984              87         84
23            Copa del Rey   1982/1983              87        268
24            Copa del Rey   1977/1978              87        279
28      FIFA U20 World Cup        1979            1470        274
29          FIFA World Cup        2022              43        106
30          FIFA World Cup        2018              43          3
31          FIFA World Cup        1990              43         55
32          FIFA World Cup        1986              43         54
33          FIFA World Cup        1974              43         51
34          FIFA World Cup        1970              43        272
35          FIFA World Cup        1962              43        270
36          FIFA World Cup        1958              43        269
37     Indian Super league   2021/2022            1238        108
38                 La Liga   2020/2021              11         90
39                 La Liga   2019/2020              11         42
40                 La Liga   2018/2019              11          4
41                 La Liga   2017/2018              11          1
42                 La Liga   2016/2017              11          2
43                 La Liga   2015/2016              11         27
44                 La Liga   2014/2015              11         26
45                 La Liga   2013/2014              11         25
46                 La Liga   2012/2013              11         24
47                 La Liga   2011/2012              11         23
48                 La Liga   2010/2011              11         22
49                 La Liga   2009/2010              11         21
50                 La Liga   2008/2009              11         41
51                 La Liga   2007/2008              11         40
52                 La Liga   2006/2007              11         39
53                 La Liga   2005/2006              11         38
54                 La Liga   2004/2005              11         37
55                 La Liga   1973/1974              11        278
56        Liga Profesional   1997/1998              81         48
57        Liga Profesional        1981              81        275
58                 Ligue 1   2022/2023               7        235
59                 Ligue 1   2021/2022               7        108
60                 Ligue 1   2015/2016               7         27
61     Major League Soccer        2023              44        107
62   North American League        1977             116         68
64          Premier League   2015/2016               2         27
65          Premier League   2003/2004               2         44
66                 Serie A   2015/2016              12         27
67                 Serie A   1986/1987              12         86
68               UEFA Euro        2024              55        282
69               UEFA Euro        2020              55         43
70      UEFA Europa League   1988/1989              35         75

In [4]:
# Count matches per competition to see which are most data-rich
for _, row in mens.iterrows():
    try:
        matches = sb.matches(competition_id=row['competition_id'], season_id=row['season_id'])
        print(f"{row['competition_name']} {row['season_name']}: {len(matches)} matches (comp_id={row['competition_id']}, season_id={row['season_id']})")
    except:
        print(f"{row['competition_name']} {row['season_name']}: ERROR")

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

1. Bundesliga 2023/2024: 34 matches (comp_id=9, season_id=281)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

1. Bundesliga 2015/2016: 306 matches (comp_id=9, season_id=27)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

African Cup of Nations 2023: 52 matches (comp_id=1267, season_id=107)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2018/2019: 1 matches (comp_id=16, season_id=4)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2017/2018: 1 matches (comp_id=16, season_id=1)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2016/2017: 1 matches (comp_id=16, season_id=2)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2015/2016: 1 matches (comp_id=16, season_id=27)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2014/2015: 1 matches (comp_id=16, season_id=26)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2013/2014: 1 matches (comp_id=16, season_id=25)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2012/2013: 1 matches (comp_id=16, season_id=24)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2011/2012: 1 matches (comp_id=16, season_id=23)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2010/2011: 1 matches (comp_id=16, season_id=22)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2009/2010: 1 matches (comp_id=16, season_id=21)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2008/2009: 1 matches (comp_id=16, season_id=41)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2006/2007: 1 matches (comp_id=16, season_id=39)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2004/2005: 1 matches (comp_id=16, season_id=37)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 2003/2004: 1 matches (comp_id=16, season_id=44)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 1999/2000: 1 matches (comp_id=16, season_id=76)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 1972/1973: 1 matches (comp_id=16, season_id=277)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 1971/1972: 1 matches (comp_id=16, season_id=71)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Champions League 1970/1971: 1 matches (comp_id=16, season_id=276)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Copa America 2024: 32 matches (comp_id=223, season_id=282)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Copa del Rey 1983/1984: 1 matches (comp_id=87, season_id=84)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Copa del Rey 1982/1983: 1 matches (comp_id=87, season_id=268)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Copa del Rey 1977/1978: 1 matches (comp_id=87, season_id=279)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

FIFA U20 World Cup 1979: 1 matches (comp_id=1470, season_id=274)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

FIFA World Cup 2022: 64 matches (comp_id=43, season_id=106)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

FIFA World Cup 2018: 64 matches (comp_id=43, season_id=3)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

FIFA World Cup 1990: 1 matches (comp_id=43, season_id=55)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

FIFA World Cup 1986: 3 matches (comp_id=43, season_id=54)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

FIFA World Cup 1974: 6 matches (comp_id=43, season_id=51)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

FIFA World Cup 1970: 6 matches (comp_id=43, season_id=272)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

FIFA World Cup 1962: 1 matches (comp_id=43, season_id=270)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

FIFA World Cup 1958: 2 matches (comp_id=43, season_id=269)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Indian Super league 2021/2022: 115 matches (comp_id=1238, season_id=108)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2020/2021: 35 matches (comp_id=11, season_id=90)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2019/2020: 33 matches (comp_id=11, season_id=42)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2018/2019: 34 matches (comp_id=11, season_id=4)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2017/2018: 36 matches (comp_id=11, season_id=1)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2016/2017: 34 matches (comp_id=11, season_id=2)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2015/2016: 380 matches (comp_id=11, season_id=27)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2014/2015: 38 matches (comp_id=11, season_id=26)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2013/2014: 31 matches (comp_id=11, season_id=25)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2012/2013: 32 matches (comp_id=11, season_id=24)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2011/2012: 37 matches (comp_id=11, season_id=23)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2010/2011: 33 matches (comp_id=11, season_id=22)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2009/2010: 35 matches (comp_id=11, season_id=21)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2008/2009: 31 matches (comp_id=11, season_id=41)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2007/2008: 28 matches (comp_id=11, season_id=40)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2006/2007: 26 matches (comp_id=11, season_id=39)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2005/2006: 17 matches (comp_id=11, season_id=38)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 2004/2005: 7 matches (comp_id=11, season_id=37)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

La Liga 1973/1974: 1 matches (comp_id=11, season_id=278)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Liga Profesional 1997/1998: 1 matches (comp_id=81, season_id=48)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Liga Profesional 1981: 1 matches (comp_id=81, season_id=275)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Ligue 1 2022/2023: 32 matches (comp_id=7, season_id=235)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Ligue 1 2021/2022: 26 matches (comp_id=7, season_id=108)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Ligue 1 2015/2016: 377 matches (comp_id=7, season_id=27)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Major League Soccer 2023: 6 matches (comp_id=44, season_id=107)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

North American League 1977: 1 matches (comp_id=116, season_id=68)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Premier League 2015/2016: 380 matches (comp_id=2, season_id=27)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Premier League 2003/2004: 38 matches (comp_id=2, season_id=44)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Serie A 2015/2016: 380 matches (comp_id=12, season_id=27)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Serie A 1986/1987: 1 matches (comp_id=12, season_id=86)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

UEFA Euro 2024: 51 matches (comp_id=55, season_id=282)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

UEFA Euro 2020: 51 matches (comp_id=55, season_id=43)

c:\tb-scouting\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

UEFA Europa League 1988/1989: 3 matches (comp_id=35, season_id=75)

## Your chosen competitions
Fill this in after running the cells above:

In [6]:
# ← FILL THIS IN after checking availability above
COMPETITIONS_TO_USE = [
    {'name': 'La Liga 2015/16',        'competition_id': 11, 'season_id': 27},
    {'name': 'Premier League 2015/16', 'competition_id': 2,  'season_id': 27},
    {'name': 'Bundesliga 2015/16',     'competition_id': 9,  'season_id': 27},
    {'name': 'Ligue 1 2015/16',        'competition_id': 7,  'season_id': 27},
    {'name': 'Serie A 2015/16',        'competition_id': 12, 'season_id': 27},
]

print('Competitions selected:')
for c in COMPETITIONS_TO_USE:
    print(f"  - {c['name']}")

Competitions selected:
  - La Liga 2015/16
  - Premier League 2015/16
  - Bundesliga 2015/16
  - Ligue 1 2015/16
  - Serie A 2015/16